b/urls.py
from django.conf.urls import url
from . import views 

urlpatterns = [
    url(r'^$', views.Thread_List_View.as_view(), name='list_thread'),
    url(r'^(?P<pk>[0-9]+)/$', views.Thread_Detail_view.as_view(), name='detail_thread'),
    url(r'^faq/$', views.Faq_View.as_view(), name='faq'),
    url(r'^complaint/$', views.complaint_view, name='complaint'),
    url(r'^posting/(?P<pk>[0-9]+)/$', views.posting_view, name='posting'),
    url(r'^show/(?P<id>[0-9]+)/$', views.show_view, name='showing'),
    url(r'^update/(?P<pk>[0-9]+)/$', views.Update_List_Post_View.as_view(), name='update_list'),
]

bord/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^b/', include('b.urls'), name='b_bord'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

b/models.py
from django.db import models
from datetime import timedelta
from django.utils import timezone
from django.shortcuts import reverse


def get_id(qs_object):
    """
    Метод возвращает айди основаный на колличестве постов
    Треды не считаются, но у каждого треда есть скрытый пост для правильной сортировки
    из-за этого цифра получается верной.

    Скорее всего будут траблы в случае одновременного создания нескольких постов
    потестить, по необходимости - переделать. 
    """
    id = Post.objects.count()
    take_id = '0' * (5 - len(str(id))) + str(id)
    return take_id


class ThreadManager(models.Manager):
    def create_thread(self, thread_text, thread_media, sid):
        """
        Функция служит оберткой для стандартного метода create
        При создании нового треда в нем сразу создается один невидимый пост
        Это делается для обеспечения правильной сортировки

        sid: session id 

        Принимает 3 параметра: текст, изображение и ключ ОП'a будущего поста.

        Так же добавляет айди, в виде строки из цифр.
        """
        thread = self.create(thread_text=thread_text, thread_media=thread_media)
        thread.post_set.create(post_text='Не смотри не меня.', post_visible=False)
        thread.thread_id = get_id(thread)
        thread.thread_op = sid
        thread.save()
        return thread


class PostManager(models.Manager):
    def create_post(self, post_thread, post_text,
                    post_media, responses, sage, op):
        """
        Обертка для стандартного метода create

        Аргументы:

        post_text: текст поста
        post_media: изображение поста
        responses: ответы на другие посты
        sage: 'сажа'
        op: 'галка ОП'a

        Добавляет к нему айди и возвращает экземляр модели Post.
        """
        last_post = post_thread.post_set.last()             # Костылемагия сортировки
        last_post.post_latest = False                       # Сортировка идет только по последнему посту
        last_post.save()
        post = self.create(post_thread=post_thread, post_text=post_text,
                           post_media=post_media, post_sage=sage)
        post.post_id = get_id(post)

        # Если пост написан автором треда - добавляет булевое значение в бд 
        if op:
            post.post_write_op = True

        # Если пост с "сажей", то поле даты, по которому сортируются посты 
        # Приравнивается к дате прошлого поста.
        # (Если оставить это значение пустым - после такого поста тред станет последним)     
        if sage:
            post.post_sys_date = last_post.post_sys_date

        # Если пост содержит ответы на другие посты
        # В цикле проверяется, это ответ на тред, или на пост и у него в поле ответов создается новая запись
        # Тоже довольно кривая реализация, по возможности переделать.    
        if responses:
            for i in responses:
                try:
                    cur_thread = Thread.objects.get(thread_id=i)
                    cur_thread.responses_set.create(response=post.post_id)
                except:
                    pass
                try:
                    cur_post = Post.objects.get(post_id=i)
                    cur_post.responses_set.create(response=post.post_id)
                except:
                    pass
        post.save()
        return post


class Thread(models.Model):
    class Meta:
        verbose_name = "тред"
        verbose_name_plural = 'треды'

    objects = ThreadManager()
    thread_id = models.CharField(blank=True, null=True, max_length=7, unique=True)
    thread_date = models.DateTimeField(auto_now_add=True)
    thread_text = models.TextField(max_length=2048)
    thread_media = models.ImageField(upload_to='b/%m', blank=False, null=False)
    thread_op = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.thread_text[:20]

    def need_delete(self):
        """
        Если последний пост в треде был опубликован более 5 часов назад - возвращает True

        Как возникнет необходимость, добавить дополнительные проверки
        например, что в треде >= 500 постов

        С помощью этого сделать автосмыв
        """
        if self.post_set.last().post_date + timedelta(hours=5) <= timezone.now():
            return True
        else:
            return False

    def delete(self, *args, **kwargs):
        self.media.delete(save=False)
        super(Thread, self).delete(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('detail_thread', kwargs={'pk': self.pk})


class Post(models.Model):
    class Meta:
        ordering = ('post_date',)
        verbose_name = "пост"
        verbose_name_plural = 'посты'

    def __str__(self):
        return self.post_text[:20]

    objects = PostManager()
    post_thread = models.ForeignKey(Thread)
    post_id = models.CharField(blank=True, null=True,  max_length=7, unique=True)
    post_date = models.DateTimeField(auto_now_add=True)
    post_sys_date = models.DateTimeField(auto_now_add=True, db_index=True,
                                         null=True, blank=True)
    post_text = models.TextField(max_length=2048)
    post_media = models.ImageField(blank=True, null=True, upload_to='b/%m')
    post_visible = models.BooleanField(default=True)
    post_latest = models.BooleanField(default=True)
    post_write_op = models.BooleanField(default=False)
    post_sage = models.BooleanField(default=False)


class Responses(models.Model):
    def __str__(self):
        return self.response
    response = models.CharField(max_length=7)
    post = models.ForeignKey(Post, blank=True, null=True)
    thread = models.ForeignKey(Thread, blank=True, null=True)


class Complaint(models.Model):
    def __str__(self):
        return self.text

    @classmethod
    def create(self, text, target):
        """ 
        Такой же алгоритм, как и в пост менеджере с ответами
        По возможности - переделать.
        """
        post, thread = None, None
        try:
            post = Post.objects.get(post_id=target)
        except:
            pass
        try:    
            thread = Thread.objects.get(thread_id=target)
        except:
            pass
        if post:
            new_comp = self.objects.create(text=text, post=post)
        elif thread:
            new_comp = self.objects.create(text=text, thread=thread)
        return

    text = models.CharField(max_length=500)
    post = models.ForeignKey(Post, blank=True, null=True)
    thread = models.ForeignKey(Thread, blank=True, null=True)

b/forms.py
from django.forms import Form, CharField, ImageField, Textarea, BooleanField


class Create_Thread_Form(Form):
    thread_text = CharField(label='Текст', max_length=1024, widget=Textarea)
    thread_media = ImageField(label='Пикча')


class Post_Form(Form):
    post_text = CharField(label='Текст', max_length=1024, widget=Textarea)
    post_media = ImageField(label='Пикча', required=False)
    post_res = CharField(max_length=480, label='hidden',
                         widget=Textarea, required=False)
    sage = BooleanField(required=False)
    op = BooleanField(required=False)


class Complaint_Form(Form):
    complaint_text = CharField(label="Что с этим постом не так?",
                               max_length=1024, widget=Textarea)
    complaint_target = CharField(label='hidden')

b/views.py
from django.views.generic import ListView, DetailView, CreateView, TemplateView
from django.http import HttpResponse
from .models import Post, Thread, Complaint
from .forms import Create_Thread_Form, Post_Form, Complaint_Form
from django.shortcuts import redirect, render_to_response, render, reverse
from b.OP import sid, set_sid


class Thread_List_View(ListView):
    page_kwarg = "page"
    context_object_name = 'thread'
    paginate_by = 10
    template_name = 'b_list.html'
    form = None

    def get(self, request, *args, **kwargs):
        self.form = Create_Thread_Form()
        self.path = request.path
        return super(Thread_List_View, self).get(request, *args, **kwargs)
    
    def get_queryset(self):
        """ 
        Параметры фильтрации и сортировки для вывода тредов в нужном порядке
        Не знаю, насколько это удачная реализация - тесты покажут. 
        """ 
        queryset = Thread.objects.order_by('-post__post_sys_date').filter(post__post_latest=True)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(Thread_List_View, self).get_context_data(**kwargs)
        context['form'] = self.form
        context['three_two_one'] = [3, 2, 1]
        context['path'] = self.path
        return context

    def post(self, request, *args, **kwargs):
        form = Create_Thread_Form(request.POST, request.FILES)
        self.path = request.path
        if form.is_valid():
            thread_text = form.cleaned_data['thread_text']
            thread_media = form.cleaned_data['thread_media']
            thread_sid = set_sid(request)
            new_thread = Thread.objects.create_thread(thread_text, thread_media, thread_sid)
            return redirect(new_thread.get_absolute_url())
        else:
            return redirect(reverse('list_thread'))

class Thread_Detail_view(DetailView):
    model = Thread
    template_name = 'b_detail.html'
    context_object_name = 'thread'

    def get(self, request, *args, **kwargs):
        self.path = request.path
        return super(Thread_Detail_view, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(Thread_Detail_view, self).get_context_data(**kwargs)
        context['path'] = self.path
        return context


class Update_List_Post_View(DetailView):
    """ 
    Класс отдающий список постов по конкретному треду
    К нему летят ajax запросы для обновления треда
    """
    model = Thread
    template_name = 'includes/b_update_list.html'


def complaint_view(request):
    """
    Метод обрабатывает ajax запросы поступающие с формы жалоб
    Хз, что произойдет если будет передана не валидная форма
    Не забыть потестить.
    """
    if request.method == 'POST':
        comp_text = request.POST.get('complaint_text', '')
        comp_target = request.POST.get('complaint_target', '')
        form = Complaint_Form({'complaint_text': comp_text,
                               'complaint_target': comp_target})
        if form.is_valid():
            Complaint.create(text=form.cleaned_data['complaint_text'],
                             target=form.cleaned_data['complaint_target'])
            return HttpResponse('ok', content_type='text/html')
        else:
            return HttpResponse('Текст ввести не забыл?', content_type='text/html')
    form = Complaint_Form()
    return render(request, 'includes/b_complaint.html', {'form': form})


def posting_view(request, pk):
    """ 
    Метод для постинга со страницы списка тредов
    К нему обращается ajax форма

    По сути, дублирует много кода из деталки
    по возможности - переделать.
    """
    if request.method == 'POST':
        if 'poster' in request.COOKIES:
            return HttpResponse('Ты постишь слишком часто, притормози.',
                                content_type='text/html')
        else:
            form = Post_Form(request.POST, request.FILES)
            if form.is_valid():
                current_thread = Thread.objects.get(pk=pk)
                post_op = False
                if form.cleaned_data['op']:
                    if current_thread.thread_op == request.session.get(sid, '') != '':
                        post_op = True                       
                post_text = form.cleaned_data['post_text']
                post_media = form.cleaned_data['post_media']
                sage = form.cleaned_data['sage']
                post_responses = form.cleaned_data['post_res']            
                if post_responses:
                    list_post_responses = post_responses.split(' ')
                    post_responses = [] 
                    for i in list_post_responses:
                        if i in post_text:
                            post_responses.append(i)
                Post.objects.create_post(post_thread=current_thread, post_text=post_text,
                                         post_media=post_media, sage=sage, op=post_op,
                                         responses=post_responses)
                response = HttpResponse('ok', content_type='text/html')
                response.set_cookie('poster', 'true', 30)
                return response
            else:
                return HttpResponse('Что ты делаешь, Карасик, не надо так',
                                    content_type='text/html')
    else:
        form = Post_Form()
        return render(request, 'includes/b_post_form.html', {'form': form})


def show_view(request, id):
    """
    Метод отдает пост, или тред в ответ на ajax запрос
    """
    post, thread = None, None
    try:
        post = Post.objects.get(post_id=id)
    except:
        pass
    try:    
        thread = Thread.objects.get(thread_id=id)
    except:
        pass
    if post:
        return render(request, 'includes/b_pop_post.html', {'qs': post})
    elif thread:
        return render(request, 'includes/b_pop_post.html', {'qs': thread})
    else:
        return HttpResponse('404, пост не найден', content_type='text/html')


class Faq_View(TemplateView):
    """
    Простой класс рендерящий страницу с примерами разметки текста

    в контекст дату передаются BBcode теги 
    """
    template_name = 'b_faq.html'   
    
    def get_context_data(self, **kwargs):
        context = super(Faq_View, self).get_context_data(**kwargs)
        context['s'] = '[s]Зачеркнутый текст[/s]'
        context['b'] = '[b]Жирный текст[/b]'
        context['u'] = '[u]Подчеркнутый текст[/u]'
        context['i'] = '[i]Курсивный текст[/i]'
        context['green'] = '[>>]Зеленый текст[/>>]'
        context['spoiler'] = '[spoiler]Текст под спойлером[/spoiler]'
        return context

b/templates/b_detail.html
{% extends 'main.html' %}
{% load bbcode_tags %}
{% load thumbnail %}

{% block additional_js %}
<script>
    var thread_pk = '{{thread.pk}}';
</script>
{% endblock %}

{% block title %}/b/ - {{ thread.thread_text|slice:":25" }} {% endblock %}

{% block main %}
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="b_logo">
        <h2>/b/ - Logo</h2>
    </div>    
</div>
<span class="controll_link">
    <a href="#up_link" id="down_link" class='down_link'>Вниз</a>
    <a href="" class="show_form_link">Открыть форму</a>
</span>
<div class="container-fluid post">
    <div class="row post_head">
        <div class="col-md-12 col-sm-12 col-xs-12 col-lg-12">
            <h5>
                <span class="anon">Анонимус</span>  
                {{ thread.thread_date|date:"l d M Y" }}
                  № <a id='{{thread.thread_id}}' class="id_link">{{ thread.thread_id }}</a>
            <span class="glyphicon glyphicon-exclamation-sign send_complaint" post="{{thread.thread_id}}"></span>
            </h5>
        </div>
    </div>
    <div class="row post_content">
        <span class="col-xs-12 col-sm-4 col-md-3 col-lg-3">
            <a href="{{thread.thread_media.url}}" class="media_content">
                <img src="{{ thread.thread_media|thumbnail_url:'list' }}" class="thread_img">
            </a>
        </span>
        <span class="col-xs-12 col-sm-8 col-md-9 col-lg-9">
            {{ thread.thread_text|bbcode|safe }}
        </span>
    </div>
    <div class="row responses">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <h5 id="res_{{q.post_id}}">
                {% if thread.responses_set.all %}
                    Ответы:
                    {% for j in thread.responses_set.all %}
                        <a href=#{{j}} class="link_show_thread" conid='{{j}}'>>>{{j}}</a>
                    {% endfor %}
                {% endif %}    
            </h5>
        </div>    
    </div>
</div>

<div class="container-fluid post_list">

</div>
<div id="controll_link_down">
    <a href="#down_link" id='up_link'>Вверх</a>
    <a href="#up_link" class="upd_link" pk='{{thread.pk}}'>Обновить</a>
    <a href="" class="show_form_link">Открыть форму</a>
</div>
{% endblock %}

{% block left %}
<div class="controll_link_left">
    <a href="#up_link" class="down_link">Вниз</a>
    <a href="" class="upd_link" pk='{{thread.pk}}'>Обновить</a>
    <a href="" class="show_form_link">Открыть форму</a>
</div>
{% endblock %}

b/templates/b_faq.html
{% extends 'main.html' %}
{% load bbcode_tags %}
{% block title %}/b/ - Разметка текста{% endblock %}

{% block main %} 

<div class="row">
	<span class="col-xs-6">{{s}}</span>
	<span class="col-xs-6">{{s|bbcode|safe}}</span>
</div>
<hr>
<div class="row">
	<span class="col-xs-6">{{b}}</span>
	<span class="col-xs-6">{{b|bbcode|safe}}</span>
</div>
<hr>
<div class="row">
	<span class="col-xs-6">{{u}}</span>
	<span class="col-xs-6">{{u|bbcode|safe}}</span>
</div>
<hr>
<div class="row">
	<span class="col-xs-6">{{i}}</span>
	<span class="col-xs-6">{{i|bbcode|safe}}</span>
</div>
<hr>
<div class="row">
	<span class="col-xs-6">{{green}}</span>
	<span class="col-xs-6">{{green|bbcode|safe}}</span>
</div>
<hr>
<div class="row">
	<span class="col-xs-6">{{spoiler}}</span>
	<span class="col-xs-6">{{spoiler|bbcode|safe}}</span>
</div>
<hr>
<h4>И другие</h4>
{% endblock %}

b/templates/b_list.html
{% extends 'main.html' %}
{% load thumbnail %}
{% load bbcode_tags %}

{% block title %}/b/ - Main page{% endblock %}

{% block main %}

<div class="row">
    <span class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="b_logo">
        <h2>/b/ - List logo</h2>
    	<hr>
    </span>
</div>

<div class="row">    
    <span class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="b_create">
        <span id='create_form_link'><<показать\скрыть форму постинга>></span>
			<form action="" method="post" enctype="multipart/form-data" id='create_form'>
				{% csrf_token %}
			    <label for="id_thread_text" class="create_label">
			    	{{form.thread_text.label}}
			    </label>
			    {{form.thread_text}}
			    <label for="id_thread_media" class="create_label">
			    	{{form.thread_media.label}}
			    </label>
			    {{form.thread_media}}
			    <input type="submit" value="Создать" id='create_subm'>
			</form>
    </span>
</div>

<hr>

{% for t in thread %}
	{% include 'includes/list_object_set.html' %}
{% endfor %}

{% include 'generic/pagination.html' %}

{% endblock %}